version: 0.2
            
phases:
  # install:
    # runtime-versions:
      # runtime: version
      # runtime: version
    # commands:
    #   - command
    #   - command
    # finally:
    #   - command
    #   - command
  pre_build:
    commands:
      - npm install
      # - command
    # finally:
    #   - command
    #   - command
  build:
    commands:
      - npm run generate
      # - command
    # finally:
    #   - command
    #   - command
  # post_build:
  #   commands:
  #     - pwd
      # - ls
  #     - cd dist
  #   finally:
  #     - command
  #     - command
# reports:
#   report-name-or-arn:
#     files:
#       - location
#       - location
#     base-directory: location
#     discard-paths: yes
#     file-format: JunitXml | CucumberJson | VisualStudioTrx | TestNGXml
artifacts:
  files:
    - dist/**/*
#     - location
#   name: artifact-name
#   discard-paths: yes
#   base-directory: location
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       name: secondary-artifact-name
#       discard-paths: yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: yes
#       base-directory: location
# cache:
#   paths:
#     - path
#     - path