export const TECH_ITEM_CATEGORIES = {
    FRAMEWORKS: 'Frameworks',
    LANGUAGES: 'Languages',
    WORLD_LANGUAGES: 'World Languages',
    DATABASES: 'Databases',
    AWS: 'AWS',
    TOOLS: 'Tools',
};

export const TECH_ITEM_CATEGORIES_SORT_ORDER = [
    TECH_ITEM_CATEGORIES.LANGUAGES,
    TECH_ITEM_CATEGORIES.FRAMEWORKS,
    TECH_ITEM_CATEGORIES.DATABASES,
    TECH_ITEM_CATEGORIES.AWS,
    TECH_ITEM_CATEGORIES.TOOLS,
    TECH_ITEM_CATEGORIES.WORLD_LANGUAGES,
];
